apiVersion: v1
description: A Fluentd Aggregator Helm chart Continuously Receive Events From The Log Forwarders. Custom gems added.
icon: file://../fluentd-logo.png
name: fluentd-aggregator
version: 0.3.1
appVersion: v1.6.3
home: https://www.fluentd.org/
sources:
- https://www.fluentd.org/
maintainers:
- name: slonob
  email: slonob@gmail.com
